services:
  jenkins:
    build: .
    image: jenkins:2.462.3-lts-jdk17
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    dns:
      - 192.168.27.10